### PR TITLE
Add cluster size and move cluster info to sidebar

### PR DESCRIPTION
**Pull request by mfleader**
change section titles, remove other app pages, and add cluster size to cluster info

### CODE REVIEW

**Comment by mfleader** [comment]
cluster-size-sidebar

**Comment by jaredoconnell** [comment]
Looks good for the most part. I'd say we can lower the font size a bit since it's in its own section now rather than trying to stand out on the right.

Should we keep UUID selection on the right?

**Comment by mfleader** [comment]
I tried the job selection in the sidebar. I think it makes sense in either place as of now since its section is relatively small and is visually separated from the insights portion by the job select box. It is also fine to put the job selection in the sidebar because the user can just pick it, and forget it. However if it is in the sidebar it seems like a little bit more of a nuisance if you want to jump around on different job selections, and have the sidebar hidden. It being in the sidebar also added clutter around the cluster info too.

**Comment by jaredoconnell** [comment]
Yeah, having it on the sidebar could de-clutter it a bit. And I mean lower the font size on the huge metric values. It made more sense to have them that big when they weren't in a small section.

**Review by jaredoconnell — APPROVED** [review]
Looks good to me. This will make it a lot clearer.

**Pull request merged**
